-- Import legacy data export into linked project using id-based upserts.
-- Source: founders-ksa-complete-export.sql

-- articles: 13 rows
INSERT INTO public.articles (id, title, slug, type, status, category, excerpt, content, metadata, country, created_at, updated_at)
VALUES (
  'a625d56d-495e-43b6-b6bf-cfb900518a3f',
  'Beyond the Hype: Core Strategic Insights for Doing Business in Saudi Arabia (Vision 2030)',
  'strategic-insights-doing-business-saudi-arabia',
  'insight',
  'public',
  'Business Strategy',
  'Saudi Arabia''s transformation under Vision 2030 has shifted the Kingdom from a difficult-to-navigate market into a primary global investment destination — but the reality of entering is nuanced.',
  '[{"paragraphs":["Saudi Arabia''s transformation under Vision 2030 has shifted the Kingdom from a difficult-to-navigate market into a primary global investment destination. However, the reality of entering the market is nuanced.","Based on expert insights from The Sovereign Group, here is a breakdown of the core knowledge, regulatory realities, and strategic shifts defining the current business landscape in the Kingdom."]},{"heading":"1. The \"Scale-Up\" Market Reality","pullQuote":"Unlike other GCC jurisdictions where you can set up a low-cost free zone entity to test the waters, entering Saudi Arabia is a capital-intensive and procedurally rigorous commitment.","paragraphs":["One of the most critical distinctions for foreign investors is that Saudi Arabia is currently positioned as a market for scale-ups, not early-stage startups.","No \"Dipping Your Toe\": Unlike other GCC jurisdictions where you can set up a low-cost free zone entity to test the waters, entering Saudi Arabia is a capital-intensive and procedurally rigorous commitment.","Prerequisites for Entry: To obtain a foreign investment license, a company typically needs to be an established entity in its home country.","100% Foreign Ownership: MISA now allows 100% foreign ownership in the majority of sectors, streamlining control for international corporations."]},{"heading":"2. The Implementation Gap: MISA vs. Operations","pullQuote":"You cannot open a corporate bank account or register on government portals without a General Manager in place — a process that can take 3 to 4 months.","paragraphs":["While obtaining the MISA license can be relatively fast, the subsequent operational setup involves a complex web of approvals.","The Commercial Registration (CR) Bottleneck: After the MISA license, obtaining the CR can be time-consuming.","The General Manager (GM) Dilemma: You cannot open a corporate bank account without a GM in place. Obtaining a visa for a foreign GM can take 3 to 4 months.","The Interim Solution: Many firms now utilize an Interim General Manager service to unlock banking and portal access immediately."]},{"heading":"3. Operational Compliance: Tax and Saudization","pullQuote":"There has been a massive influx of female talent into the workforce — highly educated and eager to work.","paragraphs":["The compliance landscape is rigorous and distinct from the wider GCC.","VAT: Saudi Arabia operates at a 15% VAT rate. Corporate Tax: There is a bifurcation based on shareholder nationality.","Saudization (Nitaqat): Compliance is not optional; failure to meet quotas results in inability to renew licenses.","The Talent Shift: A massive influx of female talent has significantly eased meeting Saudization requirements."]},{"heading":"4. The RHQ Program Evolution","pullQuote":"The initial target was 400 RHQs by 2030; the Kingdom has already surpassed 600.","paragraphs":["The RHQ program has evolved significantly since its inception.","Adoption Speed: The initial target was 400 RHQs by 2030; already surpassed 600.","Increased Flexibility: Regulations now allow operational RHQs with combined licenses."]},{"heading":"5. Infrastructure and the Vision Mindset","pullQuote":"Vision 2030 is not merely a government slogan; it is the operating system of the private sector.","paragraphs":["Riyadh is currently an expensive city for business travel — a temporary symptom of rapid growth.","Vision 2030 is the operating system of the private sector. Aligning your business narrative with this vision is a strategic necessity."]},{"heading":"Conclusion","paragraphs":["Saudi Arabia is an all-in market. It rewards those who enter with a clear business plan, sufficient capital, and professional guidance."]}]'::jsonb,
  '{"readTime":"8 min read"}'::jsonb,
  'Saudi Arabia',
  '2026-02-14T09:41:31.234677+00:00',
  '2026-02-14T09:52:44.306039+00:00'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  slug = EXCLUDED.slug,
  type = EXCLUDED.type,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  excerpt = EXCLUDED.excerpt,
  content = EXCLUDED.content,
  metadata = EXCLUDED.metadata,
  country = EXCLUDED.country,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.articles (id, title, slug, type, status, category, excerpt, content, metadata, country, created_at, updated_at)
VALUES (
  '5f86f054-a538-4ca3-9223-f5542d384071',
  'From Teenage Coder to 5 Million Downloads: The Origin Story of NJD Studio',
  'njd-studio',
  'founder_story',
  'public',
  'Gaming',
  'What began as the passion project of a 12-year-old coder has transformed into a professional gaming studio at the forefront of Saudi Arabia''s eyeball economy.',
  '[{"heading":"The Genesis: A 12-Year-Old''s Vision","pullQuote":"He wasn''t just playing games; he was building the infrastructure for them.","paragraphs":["The story of NJD Studio does not begin in a boardroom, but in the bedroom of a pre-teen enthusiast. Back in 2011, at just 11 or 12 years old, Salman was already deeply immersed in the technical world.","This technical curiosity naturally evolved. By 2016, Salman had transitioned from backend services to full-fledged game development using engines like Unity 4 and 5.","\"Hajwala\" wasn''t just a game; it was a phenomenon that garnered over 5 million downloads with zero spend on user acquisition."]},{"heading":"The Transformation: From \"Salman Studio\" to NJD","paragraphs":["For years, the operation ran under the name \"Salman Studio.\" However, 2022 marked a pivotal shift. Recognizing the need to scale and professionalize, Salman and his co-founder re-established the entity as NJD Games.","The name \"NJD\" is deeply symbolic. It references \"Najd\" (the central region of Saudi Arabia) and represents a desire to simulate the region''s 200-year historical transformation within their company culture."]},{"heading":"\"Closest to the Player\"","pullQuote":"He would personally communicate with players immediately to make changes they requested.","paragraphs":["The defining characteristic of NJD Studio''s success is their obsession with player feedback.","Salman recounts a specific habit that became company culture: he would personally communicate with players immediately to make changes they requested.","If the community votes for a specific car model, the team listens. They even test concepts by releasing 3D renders on social media before full development."]},{"heading":"Cultural Resonance: The Secret Sauce","pullQuote":"They create an emotional connection with players that foreign studios cannot replicate.","paragraphs":["Why did NJD''s racing games succeed where others failed? The answer lies in cultural authenticity.","NJD Studio leverages their local advantage. By including hyper-local details—such as King Abdullah Street—they create an emotional connection with players that foreign studios cannot replicate.","This authenticity fosters incredible retention."]},{"heading":"Key Takeaway","paragraphs":["The story of NJD Studio is a masterclass in organic growth. By combining technical expertise with an authentic respect for local culture and an open channel to their community, Salman turned a childhood hobby into a leading Saudi gaming studio."]}]'::jsonb,
  '{"intro":"In the rapidly evolving landscape of the Saudi Arabian gaming industry, few stories are as compelling as that of NJD Studio. What began as the passion project of a 12-year-old coder has transformed into a professional gaming studio at the forefront of the region''s eyeball economy.","company":"NJD Studio","founder":"Salman","milestones":[{"icon":"💻","year":"2011","title":"First Lines of Code","description":"At just 12 years old, Salman begins offering cloud services and backend networking for gamers."},{"icon":"🎮","year":"2016","title":"Game Development Begins","description":"Transitions from backend services to full game development using Unity engine."},{"icon":"🚀","year":"2018","title":"Hajwala Goes Viral","description":"Hits 5 million downloads with zero marketing spend — pure organic growth."},{"icon":"🏢","year":"2022","title":"NJD Studio is Born","description":"Rebrands from Salman Studio to NJD Games, signaling professional scale and ambition."},{"icon":"🌍","year":"2024","title":"Going Global","description":"New title Drift Tuner targets international markets in Japan and Brazil."}]}'::jsonb,
  'Saudi Arabia',
  '2026-02-14T09:48:53.308459+00:00',
  '2026-02-14T09:48:53.308459+00:00'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  slug = EXCLUDED.slug,
  type = EXCLUDED.type,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  excerpt = EXCLUDED.excerpt,
  content = EXCLUDED.content,
  metadata = EXCLUDED.metadata,
  country = EXCLUDED.country,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.articles (id, title, slug, type, status, category, excerpt, content, metadata, country, created_at, updated_at)
VALUES (
  'f945d2bd-a56d-446d-9fa6-e858fe7e5849',
  'From Passion to Production: The Story of Fahy Studios and the Rise of Saudi Gaming',
  'fahy-studios',
  'founder_story',
  'public',
  'Gaming',
  'How a Pokemon-fueled childhood dream, Vision 2030, and a strategic pivot to hybrid casual gaming built one of Saudi Arabia''s most promising production studios.',
  '[{"heading":"The Origin: A Pokemon-Fueled Dream","pullQuote":"He didn''t just play; he began modding Pokemon games, rewriting narratives, and designing characters.","paragraphs":["Every great studio has an origin story rooted in passion, and for Hani, the co-founder of Fahy Studios, that spark began with the Nintendo 64.","In his teenage years, Hani didn''t just play; he began modding Pokemon games, rewriting narratives, and designing characters.","However, the cultural landscape of the time had different plans. The expectation was rigid: become an engineer, a doctor, or a banker."]},{"heading":"The Catalyst: Vision 2030","pullQuote":"It was no longer just a childhood hobby; it was a sanctioned, supported industry.","paragraphs":["The turning point for Fahy Studios wasn''t just personal; it was national. With Vision 2030, gaming was identified as a strategic focus sector.","Hani reached out to his childhood friend, Fahad, and they decided to take a serious stab at the industry. Fahy Studios was born."]},{"heading":"What''s in a Name?","paragraphs":["The name \"Fahy\" describes someone who is \"zoned out\" or too deep in their own head—essentially, the state of flow a gamer enters when hyper-focused on play."]},{"heading":"The First Lesson: Ambition vs. Reality","pullQuote":"They paused the complex project and focused on shipping a complete product.","paragraphs":["The studio''s first project served as a critical learning experience. The team quickly realized their debut concept was too massive for a three-person team.","They made a mature pivot: they paused the complex project and focused on shipping Smash and Dash, a hyper-casual endless runner."]},{"heading":"The Strategic Pivot: Hybrid Casual and Global Partnerships","paragraphs":["Fahy Studios recognized that the Hyper-Casual market was becoming saturated. They pivoted toward Hybrid Casual games.","They partnered with Kwalee, a UK-based giant, allowing Fahy to focus on building great games while leveraging global expertise."]},{"heading":"The Future: A Sustainable Production House","paragraphs":["Today, Fahy Studios is building a sustainable production house capable of consistently churning out successful titles. From modding Pokemon roms in a bedroom to closing deals with UK publishers, their story is a blueprint for the new wave of Saudi entrepreneurs."]}]'::jsonb,
  '{"intro":"In the rapidly evolving landscape of the Middle East''s digital economy, few sectors are witnessing as much explosive growth as gaming. At the heart of this transformation in Riyadh is Fahy Studios.","company":"Fahy Studios","founder":"Hani","milestones":[{"icon":"🕹️","year":"2000s","title":"Pokemon Sparked a Dream","description":"Hani begins modding Pokemon games and running text-based RPGs on gaming forums."},{"icon":"💼","year":"2010s","title":"The Corporate Years","description":"Studies MIS and enters the corporate world with PwC and Saudi Electricity Company."},{"icon":"🎯","year":"2020","title":"Vision 2030 Catalyst","description":"Saudi gaming becomes a strategic sector. Hani reunites with co-founder Fahad."},{"icon":"📱","year":"2021","title":"First Game Ships","description":"After pivoting from an overly ambitious debut, Smash and Dash launches successfully."},{"icon":"🤝","year":"2023","title":"Global Partnership","description":"Partners with UK publisher Kwalee to scale distribution and user acquisition."}]}'::jsonb,
  'Saudi Arabia',
  '2026-02-14T09:49:12.786895+00:00',
  '2026-02-14T09:49:12.786895+00:00'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  slug = EXCLUDED.slug,
  type = EXCLUDED.type,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  excerpt = EXCLUDED.excerpt,
  content = EXCLUDED.content,
  metadata = EXCLUDED.metadata,
  country = EXCLUDED.country,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.articles (id, title, slug, type, status, category, excerpt, content, metadata, country, created_at, updated_at)
VALUES (
  '8bba8a12-8703-4930-8e4b-d7d4a88c78d8',
  'Success Is Rented, Not Owned: The Resilient Rise of Sir Alain Edene',
  'alain-edene',
  'founder_story',
  'public',
  'Healthcare',
  'From sweeping gym floors in Scotland to co-founding premier fitness clubs in Saudi Arabia, Sir Alain Edene''s journey offers a masterclass in humility and ambition.',
  '[{"heading":"The Broken Dream","pullQuote":"With damaged knees and ankles, the career he had built his identity around was over.","paragraphs":["Alain''s story begins in Cameroon, born into a poor family with a singular ambition: to become a professional football player and buy his mother a car.","For a year, he was lost. He tried working on oil rigs but eventually walked away."]},{"heading":"The Power of \"Yes\"","pullQuote":"He arrived at 5:30 AM every morning and cleaned with the same discipline he applied to sports.","paragraphs":["Alain walked into a JJB Sports Gym in Scotland and asked for a job as an instructor. He was rejected immediately.","He returned the next day, rejected again. On the third day, the manager offered him the only role available: a cleaner.","Alain said \"Yes.\" He arrived at 5:30 AM every morning and cleaned with the same discipline he applied to sports. When an instructor position opened up, he was the natural choice."]},{"heading":"The Saudi Opportunity","pullQuote":"He arrived in Saudi Arabia knowing nothing about the country.","paragraphs":["In 2008, Alain applied online for a job at a football academy in Jeddah.","A neighbor introduced him to a VIP client. Alain impressed him so much that he ended up training the man and his entire extended family for ten years.","He eventually founded Adene Fitness (2016-2018), a niche, high-end gym in Jeddah."]},{"heading":"Philosophy on Business and Leadership","pullQuote":"Building a team is like driving a bus. First, you must get the right people on the bus.","paragraphs":["Alain''s transition from trainer to founder was driven by a desire to professionalize the industry.","His leadership philosophy: building a team is like driving a bus—first, get the right people on the bus, then decide where they sit."]},{"heading":"\"Rent is Due Every Day\"","pullQuote":"Success is never owned, it is rented. And rent is due every day.","paragraphs":["He quotes: \"Success is never owned, it is rented. And rent is due every day.\"","He believes resilience is a muscle. Whether you are a CEO or a cleaner, life is hard."]},{"heading":"The Future","paragraphs":["Today, Sir Alain is focused on giving back through mentorship and consultancy. His advice: find a mentor who has the scars, learn from their mistakes, and take the faster route to the mountaintop."]}]'::jsonb,
  '{"intro":"In the world of entrepreneurship, we often hear about overnight successes. But the reality is usually a much longer, grittier road paved with rejection, reinvention, and relentless hard work.","company":"Fittin International","founder":"Sir Alain Edene","milestones":[{"icon":"⚽","year":"Early","title":"The Football Dream","description":"Born in Cameroon, Alain pursues semi-professional football in Scotland before injuries end his career."},{"icon":"🧹","year":"2005","title":"Said Yes to Cleaning","description":"Takes a janitor role at JJB Sports Gym after being rejected twice as an instructor."},{"icon":"✈️","year":"2008","title":"Lands in Saudi Arabia","description":"Applies online for a football academy job in Jeddah."},{"icon":"🏋️","year":"2016","title":"Founds Adene Fitness","description":"Launches a high-end gym in Jeddah running back-to-back sessions from dawn till dusk."},{"icon":"🌟","year":"2020","title":"Fittin International","description":"Scales to a full wellness consultancy."}]}'::jsonb,
  'Saudi Arabia',
  '2026-02-14T09:49:45.447785+00:00',
  '2026-02-15T17:21:19.796767+00:00'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  slug = EXCLUDED.slug,
  type = EXCLUDED.type,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  excerpt = EXCLUDED.excerpt,
  content = EXCLUDED.content,
  metadata = EXCLUDED.metadata,
  country = EXCLUDED.country,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.articles (id, title, slug, type, status, category, excerpt, content, metadata, country, created_at, updated_at)
VALUES (
  '98311506-4159-443a-903b-96cc3d99c943',
  'Rooted in Resilience: How Treehouse Became Riyadh''s Favorite Farm-to-Table Café',
  'treehouse',
  'founder_story',
  'public',
  'E-Commerce',
  'What started as a childhood memory of a family farm in Al Qassim has grown into one of Riyadh''s most beloved farm-to-table concepts.',
  '[{"heading":"The Origin: A Memory from Al Qassim","pullQuote":"She wanted to bring that same honest, real food to a wider audience in Riyadh.","paragraphs":["For Lulwah Al Juraiban, the concept is deeply personal. It is rooted in her childhood memories of Eid holidays spent at her family''s farm in Al Qassim.","A family member was diagnosed with cancer, and doctors advised clean, organic nutrition. Seeing the tangible impact of clean eating, Lulwah realized there was a gap in the market."]},{"heading":"The Launch: Opening on Day One of Lockdown","pullQuote":"What did I do?","paragraphs":["Treehouse opened in March 2020, on the very morning that the COVID-19 lockdown was announced in Riyadh.","Remarkably, the lockdown created a captive audience hyper-conscious about health. Treehouse sold out every single day."]},{"heading":"The Double Life: Corporate by Day, Founder by Night","pullQuote":"She is unapologetic about missing late-night social gatherings to prioritize rest and work.","paragraphs":["Lulwah is not just a founder; she is a full-time corporate employee in IT operations. For over a decade, she has maintained a demanding 9-to-5 while building her business."]},{"heading":"The Philosophy: The Farm Writes the Menu","pullQuote":"If an ingredient isn''t in season, it simply doesn''t appear on the menu.","paragraphs":["\"The farm writes the menu,\" Lulwah explains. If an ingredient isn''t in season, it simply doesn''t appear on the menu.","This philosophy extends to a deep respect for food waste. Treehouse utilizes ugly vegetables and incorporates stems and scraps into broths."]},{"heading":"The Future","paragraphs":["Today, Treehouse has expanded to multiple locations and a thriving catering business. Lulwah''s advice: Don''t wait for a manual, because one doesn''t exist."]}]'::jsonb,
  '{"intro":"In Riyadh, where the dining scene is dominated by flashy trends and international franchises, Treehouse stands as a testament to authenticity.","company":"Treehouse","founder":"Lulwah Al Juraiban","milestones":[{"icon":"🌳","year":"Childhood","title":"The Original Treehouse","description":"Eid holidays at the family farm in Al Qassim plant the seeds of a future business."},{"icon":"🥗","year":"2018","title":"Clean Eating Mission","description":"A family health crisis reveals the power of organic nutrition."},{"icon":"🔥","year":"2020","title":"Opens on Day One of Lockdown","description":"Launches the very morning COVID lockdown hits — and sells out every single day."},{"icon":"🏪","year":"2022","title":"Multiple Locations","description":"Expands across Riyadh with a thriving catering business."}]}'::jsonb,
  'Saudi Arabia',
  '2026-02-14T09:49:45.447785+00:00',
  '2026-02-14T09:49:45.447785+00:00'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  slug = EXCLUDED.slug,
  type = EXCLUDED.type,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  excerpt = EXCLUDED.excerpt,
  content = EXCLUDED.content,
  metadata = EXCLUDED.metadata,
  country = EXCLUDED.country,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.articles (id, title, slug, type, status, category, excerpt, content, metadata, country, created_at, updated_at)
VALUES (
  'c8ea605e-9d25-460c-9dd4-3e437b3446c7',
  'Leading the Feast: Faisal Shaker''s Vision for Saudi Arabia''s Culinary Future',
  'faisal-shaker',
  'founder_story',
  'public',
  'E-Commerce',
  'From a seasoned career in corporate banking to helming one of the Kingdom''s most prestigious restaurant groups, Faisal''s journey is a masterclass in leadership and adaptation.',
  '[{"heading":"From Banking to Banquets","pullQuote":"He traded financial portfolios for menus, stepping in to lead MFC full-time.","paragraphs":["Faisal''s story begins far from the kitchen. He pursued Business Administration and Economics, eventually landing in banking at Merrill Lynch, SABB, and Audi Capital for over 15 years.","In 2012, while still in banking, Faisal and his partners formed MFC. By 2017, he made the hard decision to leave banking behind."]},{"heading":"The Nozomi Lesson: A Blessing in Disguise","pullQuote":"Success isn''t just about buying a franchise; it''s about the team''s ability to execute and adapt.","paragraphs":["MFC''s first major venture was bringing Nozomi to Riyadh in 2014.","Just five months after opening, the original London location closed. Instead of panicking, they doubled down and turned it into a flagship success."]},{"heading":"The Art of Adaptation","pullQuote":"Saudi diners like to see and be seen.","paragraphs":["Saudi diners like to see and be seen—Faisal emphasizes open layouts over closed partitions.","The Saudi palette favors bold, rich flavors over subtle ones."]},{"heading":"Operations: No Vacations","pullQuote":"Operations means no vacations.","paragraphs":["\"Operations means no vacations,\" he says. His day starts at 7:30 AM and often ends past 8:00 PM.","He views his role as a facilitator for his 1,700+ employees."]},{"heading":"The Future: A Booming Kingdom","pullQuote":"The hardest part isn''t reaching the top. It''s staying there.","paragraphs":["With Vision 2030, Expo 2030, and the World Cup on the horizon, the F&B sector is exploding with opportunity.","For MFC, the recipe for staying on top: constant innovation, respect for local culture, and a championship-level team."]}]'::jsonb,
  '{"intro":"In the high-stakes world of fine dining, consistency is the ultimate currency. This is the philosophy that drives Faisal Shaker, the co-founder and CEO of Modern Food Company.","company":"Modern Food Company","founder":"Faisal Shaker","milestones":[{"icon":"🏦","year":"2000s","title":"15 Years in Banking","description":"Climbs the corporate ladder at Merrill Lynch, SABB, and Audi Capital."},{"icon":"🍽️","year":"2012","title":"MFC is Founded","description":"While still in banking, Faisal and partners form Modern Food Company."},{"icon":"🥢","year":"2014","title":"Nozomi Riyadh Opens","description":"Brings the London-based Japanese concept to Saudi Arabia."},{"icon":"🚪","year":"2017","title":"Leaves Banking for Good","description":"Goes all-in on MFC, managing 1,700+ employees."},{"icon":"🏆","year":"2030","title":"Expo & World Cup Era","description":"Positioning MFC as a leading F&B group for Saudi Arabia''s mega-events."}]}'::jsonb,
  'Saudi Arabia',
  '2026-02-14T09:50:10.555528+00:00',
  '2026-02-14T09:52:20.18679+00:00'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  slug = EXCLUDED.slug,
  type = EXCLUDED.type,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  excerpt = EXCLUDED.excerpt,
  content = EXCLUDED.content,
  metadata = EXCLUDED.metadata,
  country = EXCLUDED.country,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.articles (id, title, slug, type, status, category, excerpt, content, metadata, country, created_at, updated_at)
VALUES (
  'e7a6a118-ff96-4947-bcd9-9c71fe815c9e',
  'The Architect of Startups: Hassan Ikram on Building Resilience and Success in Saudi Arabia',
  'hassan-ikram',
  'founder_story',
  'public',
  'Consultancy',
  'From corporate finance at Morgan Stanley to founding Cotyledon Management Consultancy, Hassan Ikram''s journey offers a masterclass in resilience, strategic growth, and turning failure into a stepping stone.',
  '[{"heading":"The Serial Founder''s Origin","pullQuote":"His first venture—a restaurant in Bahrain—was purchased while he was still a sophomore in university.","paragraphs":["Hassan''s entrepreneurial journey didn''t wait for a graduation ceremony. His first venture—a restaurant in Bahrain—was purchased while still a sophomore.","Despite a successful 11-year stint in investment banking, the itch to build never left. A medical facility venture in the UAE in 2014 became one of his most valuable lessons.","He views failed founders not as liabilities, but as seasoned assets who know exactly what not to do."]},{"heading":"Cotyledon: A Three-Pillar Ecosystem","pullQuote":"They raised 5 million SAR in less than an hour.","paragraphs":["Cotyledon operates on three pillars: Consultancy, Investment, and Venture Building.","Under Cotyledon''s guidance, Saudi Kitchens grew sales to over 57 million SAR and raised 5 million SAR in less than an hour through crowdfunding."]},{"heading":"Navigating the Saudi Market: Insider Tips","pullQuote":"Don''t just start a business; start a business that aligns with the government''s goals.","paragraphs":["Align with Vision 2030. Leverage government support: The Code, Monsha''at, and Hadaf subsidies.","Hassan recently received over 900 vetted candidates through Fintech Saudi''s internship program at zero cost."]},{"heading":"The Myth of Work-Life Balance","pullQuote":"Take the time off. Mental sanity is a long-term asset.","paragraphs":["For years, Hassan operated on 18-20 hour workdays. A health scare forced him to confront burnout.","His advice now: Take the time off. Mental sanity is a long-term asset."]},{"heading":"Final Thoughts","pullQuote":"Hard work eventually pays off—just don''t give up on the drive.","paragraphs":["Hassan''s philosophy: Resilience is key. For those who do their research, leverage the ecosystem, and prioritize their well-being, the opportunities in Saudi Arabia are limitless."]}]'::jsonb,
  '{"intro":"In the thriving ecosystem of Saudi Arabia''s Vision 2030, few figures embody the spirit of serial entrepreneurship quite like Hassan Ikram.","company":"Cotyledon Management Consultancy","founder":"Hassan Ikram","milestones":[{"icon":"🍕","year":"University","title":"First Business as a Sophomore","description":"Buys a restaurant in Bahrain while still studying."},{"icon":"📊","year":"2003","title":"11 Years in Investment Banking","description":"Builds deep financial expertise at Morgan Stanley."},{"icon":"🏥","year":"2014","title":"The UAE Medical Venture","description":"A medical facility venture fails — but delivers invaluable lessons."},{"icon":"🌱","year":"2020","title":"Cotyledon is Born","description":"Launches a three-pillar startup ecosystem."},{"icon":"💰","year":"2024","title":"SAR 5M Raised in Under an Hour","description":"Portfolio company raises crowdfunding in record time."}]}'::jsonb,
  'Saudi Arabia',
  '2026-02-14T09:50:10.555528+00:00',
  '2026-02-14T09:50:10.555528+00:00'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  slug = EXCLUDED.slug,
  type = EXCLUDED.type,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  excerpt = EXCLUDED.excerpt,
  content = EXCLUDED.content,
  metadata = EXCLUDED.metadata,
  country = EXCLUDED.country,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.articles (id, title, slug, type, status, category, excerpt, content, metadata, country, created_at, updated_at)
VALUES (
  '63d8ed72-e7bb-4652-833d-446e43b51766',
  'The Long Game: Building a Business from Community Roots in Saudi Arabia',
  'race-arabia',
  'founder_story',
  'public',
  'Sports & Events',
  'In the burgeoning sports economy of Saudi Arabia, Race Arabia stands as a case study in organic growth and passion-led entrepreneurship. Founded by Nezar Al-Tuwaijri, the company transitioned from a grassroots running club into the Kingdom''s premier organizer of world-class endurance events.',
  '[{"heading":"The Pivot: From Community to Commercial Entity","pullQuote":"There was plenty of energy but nowhere to channel it. The market lacked structured goals—races—for these new athletes.","paragraphs":["Race Arabia didn''t start with a business plan; it started on the pavement. Nezar initially founded the R7 Run Club (running 7 days a week), which grew organically from three friends to over a thousand members.","The business insight came when he realized the market lacked structured goals—races—for these new athletes. Nezar identified a gap between participation (people running) and monetization (organized events). He didn''t rush to sell; he built the community first, creating a built-in customer base before the company even existed."]},{"heading":"Navigating the First Mover Disadvantage","pullQuote":"Being the first in a market is often romanticized, but there is no proof of concept.","paragraphs":["Being the first in a market is often romanticized, but Nezar highlights the brutal reality: There is no proof of concept.","In a market accustomed to endurance events being free community initiatives, convincing sponsors and participants to pay was a significant hurdle. Nezar had to educate the market on the value of professional logistics, safety, and experience.","Early mistakes included getting approvals from people who weren''t actual decision-makers, leading to cancelled events. The lesson learned was to ruthlessly verify authority and secure everything in writing, especially when dealing with complex permits for public spaces."]},{"heading":"Experience is King: The Hiring Strategy","pullQuote":"Only a runner knows the desperation of reaching an aid station or the emotion of the finish line.","paragraphs":["In the events industry, logistical perfection is the baseline, not the differentiator. Nezar argues that ''Experience is King.''","He prioritizes hiring team members who are active participants in the sport. Only a runner knows the desperation of reaching an aid station or the emotion of the finish line.","The energy of the staff dictates the energy of the participants. If the organizers view it as ''just a job,'' the event feels sterile. If they are enthusiasts, that energy becomes infectious and turns customers into advocates."]},{"heading":"The 360-Degree Feedback Loop","pullQuote":"Every complaint is a data point for growth.","paragraphs":["Scaling from small fun runs to International Trail Races in AlUla requires a rigorous commitment to improvement. Race Arabia implements a 360-degree evaluation after every single event.","Feedback is aggregated not just from participants via surveys, but also from internal teams, vendors, and government stakeholders.","Nezar views every complaint as a data point for growth. This feedback loop is what allowed them to scale operations from hundreds of runners to thousands without collapsing under logistical weight."]},{"heading":"Strategic Partnerships as Accelerators","pullQuote":"Partnering with major entities allowed Race Arabia to level up faster than they could have alone.","paragraphs":["While organic growth is healthy, Nezar emphasizes that strategic partnerships act as necessary accelerants.","Partnering with major entities like the Royal Commission for AlUla (RCU) allowed Race Arabia to level up faster than they could have alone. These partnerships provided the funding and stage to test their operational limits, moving them from local organizers to international standard-bearers.","The goal is now to move from event execution to event tourism—creating race calendars far enough in advance (12+ months) to attract international athletes, aligning directly with Vision 2030''s tourism goals."]},{"heading":"Conclusion","paragraphs":["Race Arabia''s success wasn''t an overnight sprint; it was an ultramarathon. By prioritizing community trust, obsessing over the participant experience, and navigating the regulatory landscape with patience, Nezar Al-Tuwaijri has built a sustainable business model in a sector that is just hitting its stride.","For entrepreneurs in Saudi Arabia, the message is clear: Build the community, and the market will follow."]}]'::jsonb,
  '{"intro":"In the burgeoning sports economy of Saudi Arabia, Race Arabia stands as a case study in organic growth and passion-led entrepreneurship. Founded by Nezar Al-Tuwaijri, the company transitioned from a grassroots running club into the Kingdom''s premier organizer of world-class endurance events. His journey offers critical insights for entrepreneurs looking to build in uncharted markets.","company":"Race Arabia","founder":"Nezar Al-Tuwaijri","milestones":[{"year":"2016","title":"R7 Run Club Founded","description":"Started with three friends running seven days a week, growing organically to over a thousand members."},{"year":"2018","title":"Race Arabia Launched","description":"Transitioned from community run club to a commercial entity organizing structured endurance events."},{"year":"2021","title":"AlUla Trail Race","description":"Partnered with the Royal Commission for AlUla to organize international-standard trail races."},{"year":"2024","title":"Event Tourism Vision","description":"Scaling towards 12+ month race calendars to attract international athletes, aligning with Vision 2030 tourism goals."}]}'::jsonb,
  'Saudi Arabia',
  '2026-02-14T17:35:02.875425+00:00',
  '2026-02-14T17:35:02.875425+00:00'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  slug = EXCLUDED.slug,
  type = EXCLUDED.type,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  excerpt = EXCLUDED.excerpt,
  content = EXCLUDED.content,
  metadata = EXCLUDED.metadata,
  country = EXCLUDED.country,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.articles (id, title, slug, type, status, category, excerpt, content, metadata, country, created_at, updated_at)
VALUES (
  'c87168a9-3cb5-43e2-aa52-65e984e5f07c',
  'Building a Business in Saudi Arabia: Key Insights on Culture, Connection, and Authenticity',
  'building-business-saudi-culture-connection-authenticity',
  'insight',
  'public',
  'Business Strategy',
  'Launching a startup in Saudi Arabia requires cultural intelligence, adaptability, and genuine connection. Key lessons from establishing a travel and experience design house in Riyadh.',
  '[{"heading":"Identifying the Gap: Authentic Experiences Over Standard Tourism","paragraphs":["One of the most critical steps in building a business is identifying a gap in the market. In the tourism sector, standard offerings often fail to capture the depth of local culture. While tourists might find generic safaris or city tours, there is a growing demand for authentic, immersive experiences that connect visitors with the true essence of the destination.","There is a significant appetite—both from expatriates and international tourists—to go beyond the surface. People want to understand the history, traditions, and daily life of the locals.","Instead of standard sightseeing, focus on creating \"cultural experiences.\" This could involve workshops on traditional handicrafts (like Sadu weaving), culinary experiences with local families, or tours led by passionate locals rather than scripted guides. The goal is to connect people, not just show them places."]},{"heading":"The Power of Personal Connection and Hospitality","paragraphs":["Saudi culture is deeply rooted in hospitality. For a foreign entrepreneur, the warmth and openness of the local community can be a massive catalyst for business growth.","Many international entrepreneurs arrive with preconceived notions, only to be surprised by the overwhelming generosity of the Saudi people. Being invited into homes, sharing meals, and experiencing the culture firsthand can rapidly accelerate understanding and integration.","Sharing personal journeys and authentic appreciation for the local culture on platforms like Instagram can open unexpected doors. It attracts not just followers, but potential business partners, collaborators, and clients who appreciate the genuine interest in their heritage."]},{"heading":"Adaptability and Resilience: The Start-Up Mindset","paragraphs":["The business environment in Saudi Arabia is dynamic, and success often hinges on the ability to pivot and adapt.","A business might start with one target audience (e.g., tourists) and realize there is a massive demand from another segment (e.g., locals and residents). Being willing to shift the business model to cater to these new opportunities—such as offering workshops for residents or team-building events for corporations—is crucial for sustainability.","Building a business here is a long-term game. Trust is the currency of business in the Kingdom, and it takes time to build. Entrepreneurs must be patient, resilient, and willing to navigate administrative and operational challenges without losing sight of their vision."]},{"heading":"Strategic Partnerships and Local Integration","paragraphs":["No business exists in a vacuum. Success in the Kingdom often requires strong local partnerships.","Collaborating with local partners who share the same vision can provide invaluable insights and access. Whether it is partnering with a local heritage district or finding a co-founder who understands the nuances of the market, these relationships are often the bedrock of stability and growth.","Being physically located in a vibrant community (like a heritage village or a creative hub) can provide organic visibility. A strategic location does more than just house a business; it integrates it into the daily life of the potential customer base."]},{"heading":"Bridging the Modern and the Traditional","paragraphs":["Saudi Arabia is a country of contrasts, balancing rapid modernization with deep respect for tradition. A successful business in the cultural or tourism sector must reflect this balance.","It is important to highlight that the Kingdom is not a monolith. From the historical mud houses of Diriyah to the modern skyscrapers of Riyadh, and the diverse landscapes of different regions, a business should showcase the full spectrum of the country''s identity.","There is a unique opportunity to present traditional culture in a modern, accessible way. For example, transforming heritage houses into functional business spaces or offering traditional workshops in a contemporary setting appeals to both the nostalgia of locals and the curiosity of visitors."]},{"heading":"Conclusion","paragraphs":["Building a business in Saudi Arabia is a journey of discovery. It requires an entrepreneur to be a bridge—connecting cultures, challenging stereotypes, and creating spaces where genuine human connection can thrive. By prioritizing authenticity, building trust, and remaining flexible, businesses can not only succeed but also contribute meaningfully to the Kingdom''s vibrant future."]}]'::jsonb,
  '{"readTime":"7 min read"}'::jsonb,
  'Saudi Arabia',
  '2026-02-15T13:07:37.602447+00:00',
  '2026-02-15T13:07:37.602447+00:00'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  slug = EXCLUDED.slug,
  type = EXCLUDED.type,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  excerpt = EXCLUDED.excerpt,
  content = EXCLUDED.content,
  metadata = EXCLUDED.metadata,
  country = EXCLUDED.country,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.articles (id, title, slug, type, status, category, excerpt, content, metadata, country, created_at, updated_at)
VALUES (
  'ff4ebd33-b71f-4bbf-a3de-8bab0d248a6f',
  'Two Devs, One Dream: The "Just Do It" Spirit Behind Duwit',
  'duwit-studio',
  'rising_founder',
  'public',
  'Gaming',
  'After losing control of a hit game to investors, two Indonesian founders sold everything and moved to Riyadh to rebuild — on their own terms.',
  '[{"heading":"The Catalyst: Algorithms and Hostile Takeovers","pullQuote":"I have the records of the original board game... the records of people testing my game.","paragraphs":["Duwit was born from two distinct, painful lessons that shaped the founders'' philosophy.","For Alfi, the lesson was about ownership. After a previous venture ended in a \"hostile takeover,\" he lost control of the work he had built. That experience instilled in him a rigorous discipline for documentation and IP protection. \"I have the records of the original board game... the records of people testing my game,\" Alfi says, ensuring that this time, their creation remains their own.","For Banu, the lesson was about stability. A talented developer, Banu had previously found success in the mobile gaming market. However, a sudden algorithm change on the Google Play Store slashed his game''s revenue to one-third overnight.","Realizing that the mobile Free-to-Play (F2P) market was too dependent on volatile platform algorithms and expensive user acquisition, the duo decided to pivot. They joined forces to explore new opportunities in Saudi Arabia, specifically targeting the premium PC market where quality, rather than algorithms, dictates success."]},{"heading":"The \"All-In\" Move to Riyadh","pullQuote":"You cannot attract money without a real product. Make sure you have a good product first.","paragraphs":["For Alfi and Banu, the move to Saudi Arabia wasn''t just a business trip—it was a survival strategy. Participating in the Saudi Game Champions incubator, the team is betting everything on the region''s growing ecosystem.","\"I sold my car... there is no accommodation, so I just go here,\" Alfi explains regarding the initial struggle to get established.","They are currently finalizing their Corporate Responsibility (CR) status to unlock a 200,000 SAR grant that will help stabilize the company. However, Alfi warns other founders not to see the region as easy money. \"You cannot attract money without a real product,\" he advises. \"Make sure you have a good product first\"."]},{"heading":"The Game: Chess Nuke","pullQuote":"It''s impossible to do mobile with two people.","paragraphs":["Duwit''s flagship title, Chess Nuke, is a strategy game born from a physical board game designed by the founders. They converted it into a digital prototype in just over a month and are currently testing it with 200 users.","Informed by Banu''s past experience with mobile volatility, Duwit is taking a Steam first, Mobile later approach.","\"It''s impossible to do mobile with two people,\" Alfi notes, citing the massive costs of user acquisition and live ops required for free-to-play markets. By focusing on a premium single-player experience for Desktop (targeting an August release), they plan to build a portfolio and capital before expanding."]},{"heading":"Man vs. Machine: A Unique Stance on AI","pullQuote":"You need a human for the vision.","paragraphs":["In an industry rushing to replace artists with algorithms, Duwit draws a hard line.","\"For assets, I am strictly not using AI,\" Alfi declares. He cites the importance of maintaining an artistic \"soul\" and avoiding the \"bad press\" and visibility issues on Steam associated with generative art.","However, they are using AI to empower their technical workflow. Using tools like JetBrains and Gemini, the two-man team uses AI as \"junior testers\" to check code and speed up development. \"The wrong approach is thinking ''I have AI so I don''t need a programmer,''\" Alfi says. \"That''s stupid... You need a human for the vision\"."]},{"heading":"\"Just Do It\"","paragraphs":["The road ahead is steep. The team is managing legal hurdles, finalizing the game''s UI, and preparing for a massive launch—all while navigating a new country. But the spirit of Duwit (a play on the Indonesian slang for money and the slogan \"Just Do It\") is about action.","They aren''t waiting for permission. They are building, documenting, and proving that with enough grit, two people can rebuild their dream anywhere in the world."]}]'::jsonb,
  '{"intro":"\"Don''t trust words, trust numbers.\" This is the hard-earned mantra of Akhmad Alfi Zainuddin, co-founder of the indie game studio Duwit. It is a lesson learned in the trenches of the gaming industry, where he and his co-founder, Banu Andaru Adhimuka, discovered that talent alone isn''t enough you need control. Now, the duo is all-in on Riyadh. They have left their homes in Indonesia and liquidated assets—including Alfi''s personal car to fund their dream. United in Saudi Arabia, they are building a studio founded on resilience and a strategic pivot away from the volatile mobile market.","company":"Duwit","founder":"Akhmad Alfi Zainuddin & Banu Andaru Adhimuka"}'::jsonb,
  'Saudi Arabia',
  '2026-02-17T09:12:03.835366+00:00',
  '2026-02-17T10:26:04.372678+00:00'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  slug = EXCLUDED.slug,
  type = EXCLUDED.type,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  excerpt = EXCLUDED.excerpt,
  content = EXCLUDED.content,
  metadata = EXCLUDED.metadata,
  country = EXCLUDED.country,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.articles (id, title, slug, type, status, category, excerpt, content, metadata, country, created_at, updated_at)
VALUES (
  '76ba8097-c88f-43f7-a2fb-472d3fd2366c',
  'Beyond the ''Freemium'' Trap: Engineering a Saudi-Born Global Action-RPG',
  'sabahjar-studio',
  'rising_founder',
  'public',
  'Gaming',
  'Sabahjar Studio is bypassing the mobile market to build a premium Action-Roguelike for PC, rooted in authentic Arabian mythology.',
  '[{"heading":null,"paragraphs":["In the MENA gaming market, the \"safe\" bet is well-understood: build for mobile, optimize for low-end devices, and monetize via aggressive microtransactions. It is a volume game.","Sabahjar Studio is taking a different, riskier path. Founded in January 2025, the Riyadh-based team is bypassing the local mobile market entirely to build a premium, mechanically complex Action-Roguelike for PC.","Their debut title, Djinn Scrolls, represents a test case for the Saudi ecosystem: Can a local studio successfully compete in the global \"$20 Steam game\" tier against established indie giants?"]},{"heading":"The Pivot: From 700 Million Views to Zero Players","paragraphs":["The studio''s leadership team, Bandar Majrashi (CEO) and Nour Aldeen Alqalalwah (Art Director), are not traditional game developers. They are veterans of the Saudi animation industry, best known for their work on Masameer, the Myrkott-produced series that surpassed 700 million views and secured distribution on Netflix.","This background provides the studio with a distinct \"unfair advantage\" in art direction, but it also presents a learning curve. \"We don''t want to copy-paste demons from the West,\" notes Majed Altaemi, the studio''s CTO and technical lead.","The transition from non-interactive animation to reactive game design is significant. Despite massive animation reach, game development forces them to rebuild audience, tooling, and production discipline from scratch. While the art asset quality is high, the challenge for Sabahjar has been translating that visual fidelity into gameplay that feels responsive. The team is betting that their \"Authentic Djinn\" aesthetic — rooted in smokeless fire and regional tribal lore — will provide enough differentiation to stand out in a crowded market."]},{"heading":"Technical Differentiation: The Scroll System","pullQuote":"We don''t want to copy-paste demons from the West.","paragraphs":["Mechanically, Djinn Scrolls positions itself in the \"Action-Roguelike\" genre, citing Hades and Path of Exile as benchmarks. This is a high bar; both titles are known for near-perfect combat loops.","Sabahjar''s core differentiator is the \"Scroll System.\" Rather than a standard skill tree, the game uses a combinatorial mechanic where abilities are chained via \"scrolls.\" Scrolls are socketed pre-run and modified during roguelike loops, creating exponential build paths.","Input: A basic slash. Modifier: Player links a \"Fire Scroll.\" Trigger: On critical hit, cast \"Earth Spike.\"","This system aims to create \"standardized creativity,\" allowing players to engineer their own combat builds. The technical risk (polishing a complex combinatorial system) lies in balancing: these systems are notoriously difficult to debug and prone to being \"broken\" by players in ways developers didn''t anticipate."]},{"heading":"The PC First Thesis","paragraphs":["Why reject the headline-lucrative mobile market? The founders argue it is a matter of unit economics.","\"The mobile market is incredibly expensive to break into,\" the team notes. In the current \"Post-IDFA\" mobile landscape, User Acquisition (UA) costs have skyrocketed. For a bootstrapped or seed-stage studio, the marketing budget required to acquire a profitable mobile user base is often prohibitive.","By targeting Steam (PC), Sabahjar Studio is betting on a \"high-retention, lower-volume\" model. They don''t need millions of casual downloads; they need a dedicated community of 50,000–100,000 hardcore players willing to pay an upfront premium price."]},{"heading":"The Risk Profile","paragraphs":["Despite the strong vision, the path ahead is fraught with execution risk.","Market Saturation: In 2024 alone, over 14,000 games were released on Steam. Standing out requires more than just good art; it requires a \"marketing hook.\" Successful indie titles typically need 50,000+ wishlists before launch to guarantee visibility on Steam''s \"Popular Upcoming\" list.","The \"Last 10%\" Trap: The team has achieved a Vertical Slice (50% functional completion). However, in game development, the final 10% (polishing, bug-fixing, and balancing) often consumes 50% of the timeline.","Conversion Reality: Even with strong interest, typical indie wishlist-to-purchase conversion rates hover between 5% and 15%. This leaves little margin for error in launch marketing."]},{"heading":"Ecosystem Context","paragraphs":["Sabahjar Studio is currently incubated at SGC2 (Saudi Game Center), one of the Kingdom''s primary game incubation programs under the Ministry of Communications and Information Technology that selects top teams for mentorship and funding.","Backed by a 200,000 SAR grant, the studio has the runway to reach its next milestone. But capital is only fuel. The ultimate test will be whether a team of master animators can master the brutal logic of game mechanics.","If they succeed, Djinn Scrolls won''t just be a hit game; it will be a blueprint for how Saudi studios can export culture, not just consume it."]}]'::jsonb,
  '{"stage":"Incubator","company":"Sabahjar Studio","founder":"Bandar Majrashi, Nour Aldeen Alqalalwah & Majed Altaemi","website":null,"linkedin":null,"oneLiner":"Building Djinn Scrolls — a premium PC Action-Roguelike rooted in Arabian mythology, incubated at SGC2."}'::jsonb,
  'Saudi Arabia',
  '2026-02-17T14:33:46.286729+00:00',
  '2026-02-17T14:36:13.63465+00:00'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  slug = EXCLUDED.slug,
  type = EXCLUDED.type,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  excerpt = EXCLUDED.excerpt,
  content = EXCLUDED.content,
  metadata = EXCLUDED.metadata,
  country = EXCLUDED.country,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.articles (id, title, slug, type, status, category, excerpt, content, metadata, country, created_at, updated_at)
VALUES (
  '77f730a9-4936-473d-b650-3a048b582c29',
  'The New Architecture: Shifting from Labor to Logic in the Age of AI',
  'shifting-from-labor-to-logic-ai-services',
  'insight',
  'private',
  'Growth',
  'Discover how modern service-based startups are decoupling growth from headcount by treating ''services as software'' and leveraging the 12% rule of value.',
  '[{"heading":"The New Architecture: Shifting from Labor to Logic","pullQuote":"The focus has moved from how many people are on your team to how much intelligence is embedded in your systems.","paragraphs":["For decades, the growth of a service-based business was tethered to its headcount: to earn more, you had to hire more. A new paradigm has emerged that treats ''services as software,'' allowing firms to sell automated outcomes rather than human hours.","By building internal logic engines, businesses now perform complex tasks at a fraction of traditional costs. This shift allows for profit margins exceeding 80% while delivering a bespoke service experience."]},{"heading":"The Component Framework: Building with Lego Blocks","pullQuote":"Think of these as digital Lego blocks—small, specialized AI tools and automations that can be snapped together to solve specific problems.","paragraphs":["Successful modern models rely on a ''composable'' stack rather than a single piece of software. These digital Lego blocks consist of specialized AI tools that snap together to solve specific client problems.","The framework typically includes an automated Intake Layer for data, a Processing Core where AI agents handle logic, and a polished Delivery System for the final client value."]},{"heading":"The ''Hack, Pack, Stack'' Methodology","paragraphs":["Scaling to a $10M-ready infrastructure requires a disciplined three-step evolution. First, you ''Hack'' by using existing tools to manually validate that an automation solves a genuine client problem.","Once validated, you ''Pack'' that workflow into a repeatable product, turning a messy service into a standardized asset. Finally, you ''Stack'' these products into a unified ecosystem that runs on autopilot."]},{"heading":"The 12% Rule of Value","pullQuote":"The secret to scaling to a multi-million dollar level isn''t doing everything with AI; it’s identifying that critical 12% and automating it to perfection.","paragraphs":["Analysis shows that in most professional services, roughly 12% of the tasks performed drive 80% of the actual value for the client. Identifying and automating this critical fraction is the secret to scaling without bloat.","By stripping away administrative noise, a lean team of three to five people can now produce the output of a traditional 50-person firm. This efficiency is what separates modern service providers from legacy agencies."]},{"heading":"The Skillset of the Future: Orchestration","paragraphs":["As AI tools become more accessible, the competitive advantage has shifted from technical mastery to orchestration. It is no longer about being a ''builder'' in the traditional sense.","The winners of this era are ''conductors'' who can identify market gaps and design the logical workflows to bridge them. Assembling the right components is now more valuable than writing the code from scratch."]},{"heading":"Conclusion","paragraphs":["The transition to this model represents a ''Golden Age'' for solo founders and small agencies in the region. By moving away from selling time and toward selling automated systems, it is possible to build a global, high-revenue business with minimal overhead."]}]'::jsonb,
  '{"readTime":"6 min read"}'::jsonb,
  'Saudi Arabia',
  '2026-02-28T00:04:22.293954+00:00',
  '2026-02-28T00:10:52.447173+00:00'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  slug = EXCLUDED.slug,
  type = EXCLUDED.type,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  excerpt = EXCLUDED.excerpt,
  content = EXCLUDED.content,
  metadata = EXCLUDED.metadata,
  country = EXCLUDED.country,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.articles (id, title, slug, type, status, category, excerpt, content, metadata, country, created_at, updated_at)
VALUES (
  '7ccbdd94-7933-4883-800e-d73ddcc040eb',
  'Navigating the New Tides of Global Wealth and Innovation',
  'navigating-new-tides-global-wealth-innovation',
  'insight',
  'public',
  'Business Strategy',
  'We are standing at the edge of a massive economic transformation. Those equipped with the right knowledge will define the future of wealth, technology, and value creation.',
  '[{"heading":"","pullQuote":"True power lies in understanding the unseen currents of the global market.","paragraphs":["Welcome to Insights, where we explore the profound shifts shaping our tomorrow. In a world moving faster than ever, true power lies in understanding the unseen currents of the global market.","We are standing at the edge of a massive economic transformation, and those who are equipped with the right knowledge will be the ones who define the future. Here are the core paradigms currently redefining business, technology, and wealth creation."]},{"heading":"The Great Economic Reset","pullQuote":"The future belongs to those who take a long-term view, navigating economic waves with patience and a deep understanding of market cycles.","paragraphs":["We have officially entered a new era of global economics. The days of zero-interest rates and effortless growth have transitioned into a landscape that demands sharp strategy.","Supply chains are transforming, inflation is reshaping consumer habits, and the cost of capital is fundamentally altering how businesses scale.","But within this complexity lies brilliant opportunity. It is no longer about quick, passive wins — the future belongs to those who take a long-term view, navigating these economic waves with patience and a deep understanding of market cycles."]},{"heading":"The Technology and AI Renaissance","pullQuote":"The intersection of digital intelligence and physical infrastructure is where tomorrow''s greatest fortunes are being built.","paragraphs":["Artificial Intelligence is not just a buzzword — it is a fundamental rewiring of human productivity. Historically, we have spent the vast majority of our time processing information and only a fraction creating it. The AI revolution is flipping that ratio entirely.","By automating the mundane, technology is unlocking an unprecedented era of human creativity and strategic thinking.","But to harness this magic, it requires massive real-world infrastructure — from cutting-edge data centers to immense clean energy resources. The intersection of digital intelligence and physical infrastructure is where tomorrow''s greatest fortunes are being built."]},{"heading":"The Shift from Passive to Active Value Creation","pullQuote":"The most visionary minds are not just allocating capital — they are constructing the future.","paragraphs":["There is a profound difference between simply watching the market and actively building within it. The most visionary minds are not just allocating capital; they are constructing the future.","Whether it is investing in sustainable infrastructure, driving the transition to renewable energy, or backing the next generation of disruptive startups, the focus has shifted to tangible value creation.","It is about building resilient systems that elevate communities and solve real-world problems."]},{"heading":"The Ultimate Asset: Knowledge","pullQuote":"Human ingenuity is the ultimate driver of growth — and it always will be.","paragraphs":["Amidst shifting geopolitical landscapes and evolving markets, one truth remains absolute: human ingenuity is the ultimate driver of growth.","The resilience of the entrepreneurial spirit, combined with breakthroughs in science and technology, guarantees a future filled with breathtaking possibilities.","However, reading about these monumental shifts is only the first step. To truly thrive, you must understand how to manoeuvre through them. How do you protect your assets during an economic reset? How do you position yourself to ride the wave of the AI revolution rather than be disrupted by it?"]},{"heading":"Conclusion","pullQuote":"Stop watching from the sidelines — start mastering the game.","paragraphs":["This glimpse into the global market is just the tip of the iceberg. To transform these observations into actionable, life-changing strategies, you need a deeper understanding of the mechanics at play.","Equip yourself with the brilliant insights and profound understanding you need to confidently shape your financial future. The knowledge is waiting — are you ready to dive in?"]}]'::jsonb,
  '{"readTime":"6 min read"}'::jsonb,
  'Saudi Arabia',
  '2026-03-03T06:52:17.370935+00:00',
  '2026-03-03T06:52:17.370935+00:00'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  slug = EXCLUDED.slug,
  type = EXCLUDED.type,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  excerpt = EXCLUDED.excerpt,
  content = EXCLUDED.content,
  metadata = EXCLUDED.metadata,
  country = EXCLUDED.country,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

-- submissions: 1 rows
INSERT INTO public.submissions (id, created_at, email, name, message, type)
VALUES (
  '79fd99cf-ddfd-4a0c-8834-1b3ac9f3dfaf',
  '2026-02-15T19:16:37.594079+00:00',
  'ramplywork@gmail.com',
  NULL,
  NULL,
  'subscription'
) ON CONFLICT (id) DO UPDATE SET
  created_at = EXCLUDED.created_at,
  email = EXCLUDED.email,
  name = EXCLUDED.name,
  message = EXCLUDED.message,
  type = EXCLUDED.type;

-- founder_applications: 7 rows
INSERT INTO public.founder_applications (id, created_at, founder_name, email, phone, country, city, linkedin_url, company_name, company_website, industry, one_liner, founded_date, stage, num_cofounders, cofounder_details, is_incubated, incubator_name, funding_amount, funding_type, grants_received, feature_type, message, status, age, gender, education, team_size, revenue, social_media, founder_role)
VALUES (
  '93a9f83c-8f32-4c1a-a77a-4bf867b20d4a',
  '2026-02-15T17:42:58.878122+00:00',
  'ramply work',
  'ramplywork@gmail.com',
  '9700131003',
  'saudi',
  'saudi',
  'numan',
  'nunqmdnajb',
  'nujkdnwjbf.com',
  'Gaming',
  'nuuh',
  'uhuhu',
  'series_b_plus',
  1,
  NULL,
  FALSE,
  NULL,
  '5000',
  'angel',
  '211',
  'founder_story',
  'Sorry.',
  'reviewed',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  created_at = EXCLUDED.created_at,
  founder_name = EXCLUDED.founder_name,
  email = EXCLUDED.email,
  phone = EXCLUDED.phone,
  country = EXCLUDED.country,
  city = EXCLUDED.city,
  linkedin_url = EXCLUDED.linkedin_url,
  company_name = EXCLUDED.company_name,
  company_website = EXCLUDED.company_website,
  industry = EXCLUDED.industry,
  one_liner = EXCLUDED.one_liner,
  founded_date = EXCLUDED.founded_date,
  stage = EXCLUDED.stage,
  num_cofounders = EXCLUDED.num_cofounders,
  cofounder_details = EXCLUDED.cofounder_details,
  is_incubated = EXCLUDED.is_incubated,
  incubator_name = EXCLUDED.incubator_name,
  funding_amount = EXCLUDED.funding_amount,
  funding_type = EXCLUDED.funding_type,
  grants_received = EXCLUDED.grants_received,
  feature_type = EXCLUDED.feature_type,
  message = EXCLUDED.message,
  status = EXCLUDED.status,
  age = EXCLUDED.age,
  gender = EXCLUDED.gender,
  education = EXCLUDED.education,
  team_size = EXCLUDED.team_size,
  revenue = EXCLUDED.revenue,
  social_media = EXCLUDED.social_media,
  founder_role = EXCLUDED.founder_role;

INSERT INTO public.founder_applications (id, created_at, founder_name, email, phone, country, city, linkedin_url, company_name, company_website, industry, one_liner, founded_date, stage, num_cofounders, cofounder_details, is_incubated, incubator_name, funding_amount, funding_type, grants_received, feature_type, message, status, age, gender, education, team_size, revenue, social_media, founder_role)
VALUES (
  '16b32ba0-ffde-4127-af31-290f534d1f65',
  '2026-02-16T16:42:44.321337+00:00',
  'Majed altaemi',
  'majed@voidwave.com',
  '0570551337',
  'Saudi Arabia',
  'Riyadh ',
  NULL,
  'SABAHJAR STUDIO',
  'sabahjar.co.',
  'Gaming',
  'Build the games we want to play',
  'Jan 2025',
  'mvp',
  3,
  '[{"age":"35","name":"Bandar Majrashi","education":"Artist"},{"age":"29","name":"Nour Aldean alqalalwah","education":"Animator"}]'::jsonb,
  TRUE,
  'Code sgc2',
  '200k sar',
  'grant',
  NULL,
  'rising_founder',
  NULL,
  'reviewed',
  '38',
  'Male',
  'Computer Science',
  '3',
  'Pre revenue ',
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  created_at = EXCLUDED.created_at,
  founder_name = EXCLUDED.founder_name,
  email = EXCLUDED.email,
  phone = EXCLUDED.phone,
  country = EXCLUDED.country,
  city = EXCLUDED.city,
  linkedin_url = EXCLUDED.linkedin_url,
  company_name = EXCLUDED.company_name,
  company_website = EXCLUDED.company_website,
  industry = EXCLUDED.industry,
  one_liner = EXCLUDED.one_liner,
  founded_date = EXCLUDED.founded_date,
  stage = EXCLUDED.stage,
  num_cofounders = EXCLUDED.num_cofounders,
  cofounder_details = EXCLUDED.cofounder_details,
  is_incubated = EXCLUDED.is_incubated,
  incubator_name = EXCLUDED.incubator_name,
  funding_amount = EXCLUDED.funding_amount,
  funding_type = EXCLUDED.funding_type,
  grants_received = EXCLUDED.grants_received,
  feature_type = EXCLUDED.feature_type,
  message = EXCLUDED.message,
  status = EXCLUDED.status,
  age = EXCLUDED.age,
  gender = EXCLUDED.gender,
  education = EXCLUDED.education,
  team_size = EXCLUDED.team_size,
  revenue = EXCLUDED.revenue,
  social_media = EXCLUDED.social_media,
  founder_role = EXCLUDED.founder_role;

INSERT INTO public.founder_applications (id, created_at, founder_name, email, phone, country, city, linkedin_url, company_name, company_website, industry, one_liner, founded_date, stage, num_cofounders, cofounder_details, is_incubated, incubator_name, funding_amount, funding_type, grants_received, feature_type, message, status, age, gender, education, team_size, revenue, social_media, founder_role)
VALUES (
  '2252fb9f-a8b2-4fbd-b3e7-5b0552f4f075',
  '2026-02-16T21:38:46.403153+00:00',
  'Akhmad Alfi Zainuddin',
  'teamduwit@gmail.com',
  '+6285157750425',
  'Saudi Arabia',
  NULL,
  'https://www.linkedin.com/in/akhmad-alfi-zainuddin-1909768b/',
  'Duwit',
  'https://store.steampowered.com/app/4077580/Chess_Nuke/',
  'Gaming',
  'We''re 2 super developer indie game from Riyadh to the global market with slogan "Just do it"',
  '2025',
  'mvp',
  2,
  '[{"age":"41","name":"Banu Andaru Adhimuka","education":"Visual Communication Design"}]'::jsonb,
  TRUE,
  'Saudi Game Champions 2',
  '200,000',
  'grant',
  '200,000',
  'rising_founder',
  'We''re 2 people, Banu and Alfi that risk everything of our asset to move on Riyadh and build the dream of Indie Game Studio and accepted as Saudi Game Champions 2',
  'new',
  '31',
  'Male',
  'Chemical Engineering',
  '2',
  'Pre-revenue',
  'https://x.com/ChessNukeDuwit',
  NULL
) ON CONFLICT (id) DO UPDATE SET
  created_at = EXCLUDED.created_at,
  founder_name = EXCLUDED.founder_name,
  email = EXCLUDED.email,
  phone = EXCLUDED.phone,
  country = EXCLUDED.country,
  city = EXCLUDED.city,
  linkedin_url = EXCLUDED.linkedin_url,
  company_name = EXCLUDED.company_name,
  company_website = EXCLUDED.company_website,
  industry = EXCLUDED.industry,
  one_liner = EXCLUDED.one_liner,
  founded_date = EXCLUDED.founded_date,
  stage = EXCLUDED.stage,
  num_cofounders = EXCLUDED.num_cofounders,
  cofounder_details = EXCLUDED.cofounder_details,
  is_incubated = EXCLUDED.is_incubated,
  incubator_name = EXCLUDED.incubator_name,
  funding_amount = EXCLUDED.funding_amount,
  funding_type = EXCLUDED.funding_type,
  grants_received = EXCLUDED.grants_received,
  feature_type = EXCLUDED.feature_type,
  message = EXCLUDED.message,
  status = EXCLUDED.status,
  age = EXCLUDED.age,
  gender = EXCLUDED.gender,
  education = EXCLUDED.education,
  team_size = EXCLUDED.team_size,
  revenue = EXCLUDED.revenue,
  social_media = EXCLUDED.social_media,
  founder_role = EXCLUDED.founder_role;

INSERT INTO public.founder_applications (id, created_at, founder_name, email, phone, country, city, linkedin_url, company_name, company_website, industry, one_liner, founded_date, stage, num_cofounders, cofounder_details, is_incubated, incubator_name, funding_amount, funding_type, grants_received, feature_type, message, status, age, gender, education, team_size, revenue, social_media, founder_role)
VALUES (
  'd561e8b6-a013-420f-9721-2b6f1a5934b6',
  '2026-02-16T23:36:22.11079+00:00',
  'numan',
  'NUMAN',
  NULL,
  'Saudi Arabia',
  'riyadh',
  'NUHUHSU',
  'nafash international',
  'numan',
  'Gaming',
  'nnuhnuhfuwfh',
  'UHUH',
  'mvp',
  4,
  '[{"name":"mohammed ali","role":"HUHU","email":"UHUH","linkedin":"HUHU"},{"name":"UHUH","role":"HUHU","email":"HUHU","linkedin":"UHUH"},{"name":"UHUH","role":"HUUH","email":"UHU","linkedin":"HUUH"}]'::jsonb,
  TRUE,
  'UHUHUH',
  'UHUH',
  'bootstrapped',
  'HUUHUH',
  'rising_founder',
  'AMBITION/VISION:
ufhwuhfwuh

PROBLEM SOLVING:
uhuhuh',
  'new',
  NULL,
  NULL,
  NULL,
  'UHUH',
  'UHUH',
  'UHUH',
  NULL
) ON CONFLICT (id) DO UPDATE SET
  created_at = EXCLUDED.created_at,
  founder_name = EXCLUDED.founder_name,
  email = EXCLUDED.email,
  phone = EXCLUDED.phone,
  country = EXCLUDED.country,
  city = EXCLUDED.city,
  linkedin_url = EXCLUDED.linkedin_url,
  company_name = EXCLUDED.company_name,
  company_website = EXCLUDED.company_website,
  industry = EXCLUDED.industry,
  one_liner = EXCLUDED.one_liner,
  founded_date = EXCLUDED.founded_date,
  stage = EXCLUDED.stage,
  num_cofounders = EXCLUDED.num_cofounders,
  cofounder_details = EXCLUDED.cofounder_details,
  is_incubated = EXCLUDED.is_incubated,
  incubator_name = EXCLUDED.incubator_name,
  funding_amount = EXCLUDED.funding_amount,
  funding_type = EXCLUDED.funding_type,
  grants_received = EXCLUDED.grants_received,
  feature_type = EXCLUDED.feature_type,
  message = EXCLUDED.message,
  status = EXCLUDED.status,
  age = EXCLUDED.age,
  gender = EXCLUDED.gender,
  education = EXCLUDED.education,
  team_size = EXCLUDED.team_size,
  revenue = EXCLUDED.revenue,
  social_media = EXCLUDED.social_media,
  founder_role = EXCLUDED.founder_role;

INSERT INTO public.founder_applications (id, created_at, founder_name, email, phone, country, city, linkedin_url, company_name, company_website, industry, one_liner, founded_date, stage, num_cofounders, cofounder_details, is_incubated, incubator_name, funding_amount, funding_type, grants_received, feature_type, message, status, age, gender, education, team_size, revenue, social_media, founder_role)
VALUES (
  '990c1bdd-e49f-4890-89e6-29232c99aa38',
  '2026-02-16T23:38:39.972598+00:00',
  'UHUH',
  'UHUH',
  NULL,
  'Saudi Arabia',
  'riyadh',
  'HUHUH',
  'UHUHUH',
  'UHUH',
  'Healthcare',
  'UHUHU',
  'UHUH',
  'pre_seed',
  1,
  NULL,
  FALSE,
  NULL,
  'UHUH',
  'vc',
  'HUHUH',
  'founder_story',
  'ROLE: UHUH

AMBITION/VISION:
UHUH

PROBLEM SOLVING:
HUHUH',
  'new',
  NULL,
  NULL,
  NULL,
  'UHUH',
  'UHUH',
  'HUHUH',
  NULL
) ON CONFLICT (id) DO UPDATE SET
  created_at = EXCLUDED.created_at,
  founder_name = EXCLUDED.founder_name,
  email = EXCLUDED.email,
  phone = EXCLUDED.phone,
  country = EXCLUDED.country,
  city = EXCLUDED.city,
  linkedin_url = EXCLUDED.linkedin_url,
  company_name = EXCLUDED.company_name,
  company_website = EXCLUDED.company_website,
  industry = EXCLUDED.industry,
  one_liner = EXCLUDED.one_liner,
  founded_date = EXCLUDED.founded_date,
  stage = EXCLUDED.stage,
  num_cofounders = EXCLUDED.num_cofounders,
  cofounder_details = EXCLUDED.cofounder_details,
  is_incubated = EXCLUDED.is_incubated,
  incubator_name = EXCLUDED.incubator_name,
  funding_amount = EXCLUDED.funding_amount,
  funding_type = EXCLUDED.funding_type,
  grants_received = EXCLUDED.grants_received,
  feature_type = EXCLUDED.feature_type,
  message = EXCLUDED.message,
  status = EXCLUDED.status,
  age = EXCLUDED.age,
  gender = EXCLUDED.gender,
  education = EXCLUDED.education,
  team_size = EXCLUDED.team_size,
  revenue = EXCLUDED.revenue,
  social_media = EXCLUDED.social_media,
  founder_role = EXCLUDED.founder_role;

INSERT INTO public.founder_applications (id, created_at, founder_name, email, phone, country, city, linkedin_url, company_name, company_website, industry, one_liner, founded_date, stage, num_cofounders, cofounder_details, is_incubated, incubator_name, funding_amount, funding_type, grants_received, feature_type, message, status, age, gender, education, team_size, revenue, social_media, founder_role)
VALUES (
  '8c375e43-70a7-471a-be00-1807bd0a6fda',
  '2026-02-16T23:40:12.703363+00:00',
  'jhjh',
  'hjhjh',
  NULL,
  'jhjh',
  'jhjh',
  'jhjh',
  'jjhjh',
  'jhjh',
  'Gaming',
  'jhjh',
  'jhhj',
  'mvp',
  1,
  NULL,
  FALSE,
  NULL,
  'jhhj',
  'bootstrapped',
  'jhjh',
  'founder_story',
  'ROLE: jhjhj

AMBITION/VISION:
jhjh

PROBLEM SOLVING:
jhjh',
  'featured',
  NULL,
  NULL,
  NULL,
  'hjhj',
  'jhj',
  'jhjh',
  NULL
) ON CONFLICT (id) DO UPDATE SET
  created_at = EXCLUDED.created_at,
  founder_name = EXCLUDED.founder_name,
  email = EXCLUDED.email,
  phone = EXCLUDED.phone,
  country = EXCLUDED.country,
  city = EXCLUDED.city,
  linkedin_url = EXCLUDED.linkedin_url,
  company_name = EXCLUDED.company_name,
  company_website = EXCLUDED.company_website,
  industry = EXCLUDED.industry,
  one_liner = EXCLUDED.one_liner,
  founded_date = EXCLUDED.founded_date,
  stage = EXCLUDED.stage,
  num_cofounders = EXCLUDED.num_cofounders,
  cofounder_details = EXCLUDED.cofounder_details,
  is_incubated = EXCLUDED.is_incubated,
  incubator_name = EXCLUDED.incubator_name,
  funding_amount = EXCLUDED.funding_amount,
  funding_type = EXCLUDED.funding_type,
  grants_received = EXCLUDED.grants_received,
  feature_type = EXCLUDED.feature_type,
  message = EXCLUDED.message,
  status = EXCLUDED.status,
  age = EXCLUDED.age,
  gender = EXCLUDED.gender,
  education = EXCLUDED.education,
  team_size = EXCLUDED.team_size,
  revenue = EXCLUDED.revenue,
  social_media = EXCLUDED.social_media,
  founder_role = EXCLUDED.founder_role;

INSERT INTO public.founder_applications (id, created_at, founder_name, email, phone, country, city, linkedin_url, company_name, company_website, industry, one_liner, founded_date, stage, num_cofounders, cofounder_details, is_incubated, incubator_name, funding_amount, funding_type, grants_received, feature_type, message, status, age, gender, education, team_size, revenue, social_media, founder_role)
VALUES (
  'a894f8d1-c006-4be0-a2fa-2e41c9db2317',
  '2026-02-25T03:48:08.114046+00:00',
  'numan',
  'nkn@gmail.com',
  '878787878787',
  '5454',
  '5454',
  '454',
  '5454',
  '8787',
  'EdTech',
  '4545',
  '5454',
  'pre_seed',
  2,
  '[{"age":"8787","name":"8787","education":"8787"}]'::jsonb,
  TRUE,
  '8787',
  NULL,
  'bootstrapped',
  '877',
  'rising_founder',
  '8787',
  'new',
  '54',
  'Male',
  '45454',
  '4',
  '8787',
  '8787',
  NULL
) ON CONFLICT (id) DO UPDATE SET
  created_at = EXCLUDED.created_at,
  founder_name = EXCLUDED.founder_name,
  email = EXCLUDED.email,
  phone = EXCLUDED.phone,
  country = EXCLUDED.country,
  city = EXCLUDED.city,
  linkedin_url = EXCLUDED.linkedin_url,
  company_name = EXCLUDED.company_name,
  company_website = EXCLUDED.company_website,
  industry = EXCLUDED.industry,
  one_liner = EXCLUDED.one_liner,
  founded_date = EXCLUDED.founded_date,
  stage = EXCLUDED.stage,
  num_cofounders = EXCLUDED.num_cofounders,
  cofounder_details = EXCLUDED.cofounder_details,
  is_incubated = EXCLUDED.is_incubated,
  incubator_name = EXCLUDED.incubator_name,
  funding_amount = EXCLUDED.funding_amount,
  funding_type = EXCLUDED.funding_type,
  grants_received = EXCLUDED.grants_received,
  feature_type = EXCLUDED.feature_type,
  message = EXCLUDED.message,
  status = EXCLUDED.status,
  age = EXCLUDED.age,
  gender = EXCLUDED.gender,
  education = EXCLUDED.education,
  team_size = EXCLUDED.team_size,
  revenue = EXCLUDED.revenue,
  social_media = EXCLUDED.social_media,
  founder_role = EXCLUDED.founder_role;

-- kickstart_signups: 1 rows
INSERT INTO public.kickstart_signups (id, created_at, name, email, whatsapp, business_idea, help_needed, status)
VALUES (
  '47faf622-ca33-47bc-9ef8-a6f03172f856',
  '2026-02-26T01:42:25.871575+00:00',
  'numan',
  '54544numan@gmail.com',
  '5445',
  '5454',
  ARRAY['Logo & Branding','Instagram & Social Media']::text[],
  'contacted'
) ON CONFLICT (id) DO UPDATE SET
  created_at = EXCLUDED.created_at,
  name = EXCLUDED.name,
  email = EXCLUDED.email,
  whatsapp = EXCLUDED.whatsapp,
  business_idea = EXCLUDED.business_idea,
  help_needed = EXCLUDED.help_needed,
  status = EXCLUDED.status;

-- ══════════════════════════════════════
-- END OF EXPORT
-- ══════════════════════════════════════
